### ISSUE TITLE
getOrder method not implemented

### ISSUE THREAD

**Issue by dutu** [bausmeier/node-bitx#11]
Can you implement the method `getOrder` (Get an order by its id).
Thanks!

**Comment by bausmeier** [comment]
Thanks for opening these tickets. I have seen them, but I don't have time at the moment so either you can implement it and open a PR, or you will have to wait until I get a chance.

**Comment by dutu** [comment]
Ok, thanks, done. 
Also tested towards the exchange, works fine

**Comment by bausmeier** [comment]
I have released v1.5.0 with this change.

**Comment by dutu** [comment]
thanks
