### ISSUE TITLE
pair parameter for getTicker

### ISSUE THREAD

**Issue by dutu** [bausmeier/node-bitx#4]
Would it be possible to add `pair` parameter as option to `getTicker`, `getOrderBook`, `getTrades` and `getOrderList`, rather then using the `pair` from constructor?

**Comment by dutu** [comment]
Just noted that as per official API documentation pair is not optional for getTicker, getOrderBook,...
If pair is missing the native API returns an error. Not sure if you'd want to change the behavior as this change will introduce backwards compatibility issues. It is no problem for me if you don't change... up to you

**Comment by bausmeier** [comment]
If the pair option is not provided then it defaults to `XBTZAR` so it shouldn't be missing unless you explicity remove it. See https://github.com/bausmeier/node-bitx/blob/fafab1c7ade526ef14656c1beb2214c7f8f615a5/lib/BitX.js#L26.

**Comment by dutu** [comment]
yes, however as per native API the parameter is mandatory and an error is returned if mission. In your implementation it defaults to XBTZAR instead of returning error

**Comment by bausmeier** [comment]
Oh I see. I prefer to have a default value but I can see why it might cause confusion. I will think about removing the default.

**Comment by dutu** [comment]
No, problem. 
Removing the default will create backward compatibility issues for your module (in case someone is using it without parameter to get XBTZAR info). Perhaps better to change it when you have other reasons for a major change

**Comment by bausmeier** [comment]
Good idea. I will do that.
