### ISSUE TITLE
try/catch and callback confusion

### ISSUE THREAD

**Issue by dutu** [bausmeier/node-bitx#6]
callback is called in the try statement in BitX.js at line 72.
If the callback function throws an exception, then callback is executed again in catch.

Possible solution 
```js
       try {
          response = JSON.parse(response);
        } catch (err) {
          callback(err);
          return;
        }
        if (response["error"]) {
            callback(new Error(response.error));
          } else {
            callback(null, response);
          }

```

**Comment by bausmeier** [comment]
Thanks for pointing that out - it should be fixed now.

**Comment by dutu** [comment]
Looks good. Thanks for the fast response and fix
